# -*- mode: snakemake -*-

# Directories
RAW_DIR = "../../../data/raw/Nojus/genetic_data_raw"
QC_DIR = "../../../data/intermediate/2-Genetic-Data-QC"

#CHROMOSOMES = list(range(1, 23))
CHROMOSOMES = [21, 22, 23]

def get_padded(wildcards):
  """Return padded number for input filename (01, 02, or 23)"""
  chrom = int(wildcards.chr)
  if chrom < 10:
      return f"0{chrom}"
  else:
      return str(chrom)

rule all:
  "The default rule"
  input: f"{QC_DIR}/2.2-SL/SL_QC_list.irem"

rule variant_qc:
  "run variant-level QC"
  input:
        bgen = lambda w: f"{RAW_DIR}/filtered_{get_padded(w)}.bgen",
        sample = f"{RAW_DIR}/swapped.sample"
  output:
        output = f"{QC_DIR}/2.1-VL/VL_{{chr}}.bgen"
  params:
        out_prefix = f"{QC_DIR}/2.1-VL/VL_{{chr}}"
  shell:"""
  . 2.1-Variant-Level-QC.sh {input.bgen} {input.sample} {params.out_prefix}
  """

rule combine_bgens:
  "combine individual chromosome data into one bgen file"
  input:
        bgens = expand(f"{QC_DIR}/2.1-VL/VL_{{chr}}.bgen", chr=CHROMOSOMES),
        sample = f"{RAW_DIR}/swapped.sample"
  output:
       combined_bgen = f"{QC_DIR}/2.2-SL/combined.bgen" 
  params:
        qc_dir = QC_DIR
  shell:"""
. 2.2.1-Combine-BGENs.sh {params.qc_dir}/2.1-VL {input.sample} {params.qc_dir}/2.2-SL
"""

rule generate_slqc_list:
  "generate a list of samples to remove based on sample-level qc"
  input:
        combined_bgen = f"{QC_DIR}/2.2-SL/combined.bgen"
        sample = f"{RAW_DIR}/swapped.sample"
  output:
        output = f"{QC_DIR}/2.2-SL/SL_QC.id"
  params:
        out_prefix = f"{QC_DIR}/2.2-SL/SL_QC"
  shell:"""
  . 2.2.2-Generate-SLQC-List.sh {input.bgen} {input.sample} {params.out_prefix}
  """

rule keep_slfiltered_samples:
  "keep samples that passed the filter "
  input:
        bgens = expand(f"{QC_DIR}/2.1-VL/VL_{{chr}}.bgen", chr=CHROMOSOMES),
        sample = f"{RAW_DIR}/swapped.sample",
        ids_to_keep = f"{QC_DIR}/2.2-SL/SL_QC.id"
  output:
        output = f"{QC_DIR}/2.2-SL/SL_{{chr}}.bgen" 
  params:
        out_prefix = f"{QC_DIR}/2.2-SL/SL_{{chr}}"
  shell:"""
. 2.2.3-Keep-Samples.sh {input.bgens} {input.sample} {input.ids_to_keep} {params.out_prefix}
"""

rule find_sex_mismatch:
  "find samples with mismatched sex"
  input:
        bgen23 = f"{QC_DIR}/2.2-SL/SL_23.bgen"
        sample = f"{QC_DIR}/2.2-SL/SL_23.sample"
  output:
        output = f"{QC_DIR}/2.3-SM/SM.sexcheck"
  params:
        out_prefix = f"{QC_DIR}/2.3-SM/SM"
  shell:"""
  . 2.3.1-Sex-Mismatch-Find.sh {input.bgen23} {input.sample} {params.out_prefix}
  """

rule remove_sex_mismatch:

rule problematic_variants_qc:

rule pruning: