# -*- mode: snakemake -*-

# Directories
RAW_DIR = "../../data/raw/Nojus"

QC_DIR = "../../data/intermediate/2-Genetic-Data-QC"
INTERMEDIATE_DIR = "../../data/intermediate"

# define chromosome patterns to parallelise process

CHROMOSOMES = list(range(1, 23+1))

def get_padded(wildcards):
  """Return padded number for input filename (01, 02, or 23)"""
  chrom = int(wildcards.chr)
  if chrom < 10:
      return f"0{chrom}"
  else:
      return str(chrom)

rule all:
  "The default rule"
  input:         
        eigenval = f"{QC_DIR}/2.5-PCA/genetic_pcs20.eigenval",
        eigenvec = f"{QC_DIR}/2.5-PCA/genetic_pcs20.eigenvec"

###################################################################################################
# Recoding NAs
###################################################################################################

# 1. Recode NAs and create a sample sheet for eligible participants

rule recode_nas:
  "recode NAs and create a sample sheet for eligible participants"
  input:
        pheno = f"{RAW_DIR}/B4891_Goudswaard_5Jan26.sav",
        omicsid = f"{RAW_DIR}/B4891_OmicsIDs_5Jan26.sav"
  output:
        pheno = f"{INTERMEDIATE_DIR}/1-Recoded-NAs-Pheno/pheno_nas_recoded.csv",
        sampleid = f"{INTERMEDIATE_DIR}/1-Recoded-NAs-Pheno/eligible_sample.id"
  shell:"""
  mkdir -p {INTERMEDIATE_DIR}/1-Recoded-NAs-Pheno
  Rscript 1-Recoding-NAs.R/1.1-Recoding-NAs.R {input.pheno} {input.ommicsid} {output.pheno} {output.sampleid}
  """

###################################################################################################
# Genetic QC + PCA
###################################################################################################




# 2.1 Variant-level-QC

rule variant_qc:
  "run variant-level QC"
  input:
        bgen = lambda w: f"{RAW_DIR}/genetic_data_raw/filtered_{get_padded(w)}.bgen",
        sample = f"{RAW_DIR}/genetic_data_raw/swapped.sample",
        eligible_sample = f"{INTERMEDIATE}/1-Recoded-NAs-Pheno/eligible_sample.id"
  output:
        pgen = f"{QC_DIR}/2.1-VL/VL_{{chr}}.pgen",
        psam = f"{QC_DIR}/2.1-VL/VL_{{chr}}.psam",
        pvar = f"{QC_DIR}/2.1-VL/VL_{{chr}}.pvar",
        log = f"{QC_DIR}/2.1-VL/VL_{{chr}}.log"
  params:
        out_prefix = f"{QC_DIR}/2.1-VL/VL_{{chr}}",
        chr_num = "{chr}"
  shell:"""
  mkdir -p {QC_DIR}/2.1-VL
  . 2-Genetic-QC/2.1-Variant-Level-QC.sh {input.bgen} {input.sample} {input.eligible_sample} {params.chr_num} {params.out_prefix}
  """

# 2.2 Sample-level QC

rule generate_slqc_list:
  "generate list of samples that passed sample-level qc and sex-check list"
  input:
        pgen = expand(f"{QC_DIR}/2.1-VL/VL_{{chr}}.pgen", chr=CHROMOSOMES),
        psam = expand(f"{QC_DIR}/2.1-VL/VL_{{chr}}.psam", chr=CHROMOSOMES),
        pvar = expand(f"{QC_DIR}/2.1-VL/VL_{{chr}}.pvar", chr=CHROMOSOMES)
  output:
        slqc_list = f"{QC_DIR}/2.2-SL/SL_QC.id",
        sm_list = f"{QC_DIR}/2.2-SL/SL_QC.sexcheck"
  resources: mem_mb = 60000, threads = 20, runtime = 25
  params:
        in_dir = f"{QC_DIR}/2.1-VL",
        out_prefix = f"{QC_DIR}/2.2-SL/SL_QC"
  shell:"""
  mkdir -p {QC_DIR}/2.2-SL
  . 2-Genetic-QC/2.2.1-Generate-SLQC-List.sh {params.in_dir} {params.out_prefix}
  """

rule keep_slfiltered_samples:
  "keep samples that passed the filters"
  input:
        pgen = f"{QC_DIR}/2.1-VL/VL_{{chr}}.pgen",
        psam = f"{QC_DIR}/2.1-VL/VL_{{chr}}.psam",
        pvar = f"{QC_DIR}/2.1-VL/VL_{{chr}}.pvar",
        slqc_list = f"{QC_DIR}/2.2-SL/SL_QC.id",
        sm_list = f"{QC_DIR}/2.2-SL/SL_QC.sexcheck"
  output:
        pgen = f"{QC_DIR}/2.2-SL/SL_{{chr}}.pgen",
        psam = f"{QC_DIR}/2.2-SL/SL_{{chr}}.psam",
        pvar = f"{QC_DIR}/2.2-SL/SL_{{chr}}.pvar",
        log = f"{QC_DIR}/2.2-SL/SL_{{chr}}.log"
  params:
        in_prefix = f"{QC_DIR}/2.1-VL/VL_{{chr}}",
        out_prefix = f"{QC_DIR}/2.2-SL/SL_{{chr}}"
  shell:"""
  . 2-Genetic-QC/2.2.2-Apply-SL-List.sh {params.in_prefix} {input.slqc_list} {input.sm_list} {params.out_prefix}
  """

# 3. Remove problematic variants

rule problematic_variants_qc:
  "remove problematic variants"
  input:
        pgen = f"{QC_DIR}/2.2-SL/SL_{{chr}}.pgen",
        psam = f"{QC_DIR}/2.2-SL/SL_{{chr}}.psam",
        pvar = f"{QC_DIR}/2.2-SL/SL_{{chr}}.pvar"
  output:
        pgen = f"{QC_DIR}/2.3-PV/PV_{{chr}}.pgen",
        psam = f"{QC_DIR}/2.3-PV/PV_{{chr}}.psam",
        pvar = f"{QC_DIR}/2.3-PV/PV_{{chr}}.pvar",
        log = f"{QC_DIR}/2.3-PV/PV_{{chr}}.log"
  params:
        in_prefix = f"{QC_DIR}/2.2-SL/SL_{{chr}}",
        out_prefix = f"{QC_DIR}/2.3-PV/PV_{{chr}}"
  shell:"""
  mkdir -p {QC_DIR}/2.3-PV
  . 2-Genetic-QC/2.3-Problematic-Variants-QC.sh {params.in_prefix} {params.out_prefix}
  """

# 4. Pruning

rule pruning:
  "combine datasets and prune"
  input:
        pgen = expand(f"{QC_DIR}/2.3-PV/PV_{{chr}}.pgen", chr=CHROMOSOMES),
        psam = expand(f"{QC_DIR}/2.3-PV/PV_{{chr}}.psam", chr=CHROMOSOMES),
        pvar = expand(f"{QC_DIR}/2.3-PV/PV_{{chr}}.pvar", chr=CHROMOSOMES)
  output:
        pgen_unpruned = f"{QC_DIR}/2.4-Pruning/clean_unpruned.pgen",
        psam_unpruned = f"{QC_DIR}/2.4-Pruning/clean_unpruned.psam",
        pvar_unpruned = f"{QC_DIR}/2.4-Pruning/clean_unpruned.pvar",
        log_unpruned = f"{QC_DIR}/2.4-Pruning/clean_unpruned.log",
        pgen_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.pgen",
        psam_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.psam",
        pvar_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.pvar",
        log_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.log"        
  resources: threads = 20, runtime = 25
  params:
        in_dir = f"{QC_DIR}/2.3-PV",
        unpruned_prefix = f"{QC_DIR}/2.4-Pruning/clean_unpruned",
        pruned_prefix = f"{QC_DIR}/2.4-Pruning/clean_pruned"
  shell:"""
  mkdir -p {QC_DIR}/2.4-Pruning
  . 2-Genetic-QC/2.4-Pruning.sh {params.in_dir} {params.unpruned_prefix} {params.pruned_prefix}
  """

# 5. PCA
rule pca:
  "PCA analysis of pruned variants"
  input:
        pgen_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.pgen",
        psam_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.psam",
        pvar_pruned = f"{QC_DIR}/2.4-Pruning/clean_pruned.pvar"
  output:
        eigenval = f"{QC_DIR}/2.5-PCA/genetic_pcs20.eigenval",
        eigenvec = f"{QC_DIR}/2.5-PCA/genetic_pcs20.eigenvec"
  resources: threads = 20, runtime = 30
  params:
        pruned_prefix = f"{QC_DIR}/2.4-Pruning/clean_pruned",
        pca_prefix = f"{QC_DIR}/2.5-PCA/genetic_pcs20"
  shell:"""
  mkdir -p {QC_DIR}/2.4-Pruning
  
  module add apps/plink2
  plink2 \
  --pfile {params.pruned_prefix} \
  --pca 20 \
  --out {params.pca_prefix}
  """

# 0. Cleaning

rule clean1:
  "clean directory 1-Pheno-NAs-Recoded"
  shell:"""
  rm -rf {INTERMEDIATE_DIR}/1-Pheno-NAs-Recoded
  """

rule clean_VL:
  "clean directory 2.1-VL"
  shell:"""
  rm -rf {QC_DIR}/2.1-VL
  """
rule clean_SL:
  "clean directory 2.2-SL"
  shell:"""
  rm -rf {QC_DIR}/2.2-SL
  """
rule clean_PV:
  "clean directory 2.3-PV"
  shell:"""
  rm -rf {QC_DIR}/2.3-PV
  """
rule clean_pruning:
  "clean directory 2.4-Pruning"
  shell:"""
  rm -rf {QC_DIR}/2.4-Pruning
  """
rule clean_all:
  "clean all intermediate genetic QC directories (keep final result))"
  shell:"""
  snakemake -c1 clean_VL clean_SL clean_PV
  """